application: cclphp
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:
- url: /*
  script: index.php
  secure: optional

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
